### ISSUE TITLE
Possibility to use fanout exchange (broadcast)

### ISSUE THREAD

**Issue by fernandes** [simplybusiness/rabbit_feed#21]
I started using rabbit_feed for some tests (really great gem btw, makes damm easy to use RabbitMQ), and I'd like to broadcast a message to all workers (as I've seen on RabbitMQ its using the fanout exchange), is there any way to do this using rabbit_feed?

ps: Sorry if its a dummy question, I'm new to RabbitMQ and just looked into rabbit_feed source to discover if its possible, but found nothing about

thank you

**Comment by joshuafleck** [comment]
Hi @fernandes - thank you!

RabbitFeed does not use a fanout exchange because that would violate one of the main principles of RabbitFeed: The consumers define which events they want routed to them.

There is a way to get this behaviour using RabbitFeed as-is: In your consumer, you can use wildcards to allow you to subscribe to all events from all applications. An example of how to configure the event routing to allow this can be found [here](https://github.com/simplybusiness/rabbit_feed#wildcards). Please let me know if this works for you!

**Comment by fernandes** [comment]
but as I've seen...

event producer: user.created
event consumer 1: user.*
event consumer 2: user.created

just one of them will receive once rabbit feed use a topic exchange on rabbitmq, no?

ps: I'm new to mq and rabbitmq, just an assumption after reading the rabbitmq getting started and bunny docs

thank you

**Comment by joshuafleck** [comment]
> just one of them will receive once rabbit feed use a topic exchange on rabbitmq, no?

Both consumer 1 and consumer 2 will receive the user.created event. The reason that both consumers will receive the event is that RabbitFeed uses a [topic exchange](http://rubybunny.info/articles/exchanges.html#topic_exchanges) and creates a separate queue for each consumer application. 

> Topic exchanges route messages to one or many queues based on matching between a message routing key and the pattern that was used to bind a queue to an exchange. The topic exchange type is often used to implement various publish/subscribe pattern variations.

> Topic exchanges are commonly used for the multicast routing of messages.

The key to ensuring the message is routed to both consumers is to provide a unique application name to each consumer in its `rabbit_feed.yml` file. For example, using the example apps from the RabbitFeed project, the rails example app has an application name of `rails_app` (see its [`rabbit_feed.yml`](https://github.com/simplybusiness/rabbit_feed/blob/master/example/rails_app/config/rabbit_feed.yml)), whilst the non rails example app has an application name of `non_rails_app` (see its [`rabbit_feed.yml`](https://github.com/simplybusiness/rabbit_feed/blob/master/example/non_rails_app/config/rabbit_feed.yml)). RabbitFeed will create a separate queue for each consumer application (based on its application name) and will be able to take advantage of multicast routing. As RabbitFeed is designed to support one application per process, each consumer worker would need to run in its own process.

**Comment by fernandes** [comment]
hummmm so instead of fanout its gonna deliver 2 messages to 2 queues? That's correct? Amazing!

Because using fanout with many nodes processing the same queue would be hell to avoid race conditions... really good to know that rabbit feed works this way, now for me its perfect!

great job here, I'm gonna adopt it for rabbitmq for sure!

thank you for all information @joshuafleck :+1:

**Comment by joshuafleck** [comment]
> hummmm so instead of fanout its gonna deliver 2 messages to 2 queues? That's correct? Amazing!

Yes, that is correct. Please let me know if you need any additional help with setting this up!

> great job here, I'm gonna adopt it for rabbitmq for sure!

Thank you! Glad to hear!

I'm going to close this issue for now, but please feel free to re-open if this is not working for you.

**Comment by fernandes** [comment]
thats perfect... thank you very much!
